export const chartData = [
  {
    color: "bg-extraverted",
    shadowColor: "extraverted",
    leftContext: "extraverted",
    rightContext: "introverted",
    leftColor: "text-extraverted font-bold",
    rightColor: "text-percentage",
    left: "66%",
    right: "34%",
  },
  {
    color: "bg-intuitive",
    shadowColor: "intuitive",
    leftContext: "intuitive",
    rightContext: "observant",
    leftColor: "text-intuitive font-bold",
    rightColor: "text-percentage",
    left: "54%",
    right: "46%",
  },
  {
    color: "bg-thinking",
    shadowColor: "thinking",
    leftContext: "thinking",
    rightContext: "feeling",
    leftColor: "text-thinking font-bold",
    rightColor: "text-percentage",
    left: "55%",
    right: "45%",
  },
  {
    chartColor: "bg-prospecting",
    shadowColor: "prospecting",
    leftContext: "judging",
    rightContext: "prospecting",
    leftColor: "text-percentage",
    rightColor: "text-prospecting font-bold",
    left: "43%",
    right: "57%",
  },
  {
    chartColor: "bg-turbulent",
    shadowColor: "turbulent",
    leftContext: "assertive",
    rightContext: "turbulent",
    leftColor: "text-percentage",
    rightColor: "text-turbulent font-bold",
    left: "47%",
    right: "53%",
  },
];
